server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board2
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp